/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * CRM API GetMoto
 * API para gestão de oficina de motos - Sistema de CRM completo
 * OpenAPI spec version: 1.0.0
 */

export interface Service {
  id?: string;
  customer_name?: string;
  vehicle_id?: number;
  professional_name?: string;
  description?: string;
  status?: string;
  estimated_labor_cost?: number;
}
